// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ourWinch.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231012002313_MechanicalUpdate1")]
    partial class MechanicalUpdate1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CheckItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MechanicalChecklistId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MechanicalChecklistId");

                    b.ToTable("CheckItems");
                });

            modelBuilder.Entity("MechanicalChecklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MechanicalChecklists");
                });

            modelBuilder.Entity("ourWinchSist.Models.ServiceOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etternavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feilbeskrivelse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fornavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Garanti")
                        .HasColumnType("bit");

                    b.Property<string>("KommentarFraKunde")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobilNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MottattDato")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ordrenummer")
                        .HasColumnType("int");

                    b.Property<string>("Produkttype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Reperasjon")
                        .HasColumnType("bit");

                    b.Property<string>("Serienummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Servis")
                        .HasColumnType("bit");

                    b.Property<string>("Årsmodell")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceOrders");
                });

            modelBuilder.Entity("CheckItem", b =>
                {
                    b.HasOne("MechanicalChecklist", "MechanicalChecklist")
                        .WithMany("CheckItems")
                        .HasForeignKey("MechanicalChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MechanicalChecklist");
                });

            modelBuilder.Entity("MechanicalChecklist", b =>
                {
                    b.Navigation("CheckItems");
                });
#pragma warning restore 612, 618
        }
    }
}
