version: '3.8'
services:
  webapp:
    build: .
    environment:
      - ConnectionStrings__DefaultConnection=Server=tcp:nosteddb.database.windows.net,1433;Initial Catalog=NostedDB;Persist Security Info=False;User ID=nostedAdmin;Password=icardi1990!;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=180;
    ports:
      - "80:5002"
      - "443:5002" 

    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'localnosted'
      MYSQL_USER: 'nostedDB'
      MYSQL_PASSWORD: 'icardi1990!'
      MYSQL_ROOT_PASSWORD: 'icardi1990!'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: