version: '3.8'
services:
  webapp:
    build: .
    environment:
      - ConnectionStrings__DefaultConnection=Server=tcp:nosteddb.database.windows.net,1433;Initial Catalog=NostedDB;Persist Security Info=False;User ID=nostedAdmin;Password=icardi1990!;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=180;
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'myDb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'my-secret-pw'
      MYSQL_ROOT_PASSWORD: 'my-secret-pw'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
